package com.beauty.entity.security;

// default package
// Generated 2015-7-19 19:51:33 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BeautyAuthorityResource generated by hbm2java
 */
@Entity
@Table(name = "beauty_authority_resource", catalog = "sec")
public class BeautyAuthorityResource implements java.io.Serializable {

	/**
	 * @Fields serialVersionUID
	 */
	private static final long serialVersionUID = 1L;
	
	
	private Long id;
	private Long resourceId;
	private Long authorityId;

	public BeautyAuthorityResource() {
	}

	public BeautyAuthorityResource(Long resourceId, Long authorityId) {
		this.resourceId = resourceId;
		this.authorityId = authorityId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	@Column(name = "resourceId")
	public Long getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(Long resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "authorityId")
	public Long getAuthorityId() {
		return this.authorityId;
	}

	public void setAuthorityId(Long authorityId) {
		this.authorityId = authorityId;
	}

}
