package com.beauty.dao.security2;

import com.beauty.entity.security2.GroupReRole;


public interface GroupReRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beauty_group_role
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beauty_group_role
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    int insert(GroupReRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beauty_group_role
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    int insertSelective(GroupReRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beauty_group_role
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    GroupReRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beauty_group_role
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    int updateByPrimaryKeySelective(GroupReRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beauty_group_role
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    int updateByPrimaryKey(GroupReRole record);
}