package com.beauty.dao.security2;

import com.beauty.entity.security2.UserReGroup;

public interface UserReGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beauty_user_group
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beauty_user_group
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    int insert(UserReGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beauty_user_group
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    int insertSelective(UserReGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beauty_user_group
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    UserReGroup selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beauty_user_group
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    int updateByPrimaryKeySelective(UserReGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table beauty_user_group
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    int updateByPrimaryKey(UserReGroup record);
}