package com.beauty.entity.security2;

import com.beauty.base.security.CommonEntity;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Authority extends CommonEntity {

	/**
	 * @Fields serialVersionUID
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column beauty_authority.authority_name
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	private String authorityName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column beauty_authority.authority_code
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	private String authorityCode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column beauty_authority.group_id
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	private Long groupId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column beauty_authority.group_name
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	private String groupName;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column beauty_authority.authority_name
	 *
	 * @return the value of beauty_authority.authority_name
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public String getAuthorityName() {
		return authorityName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column beauty_authority.authority_name
	 *
	 * @param authorityName
	 *            the value for beauty_authority.authority_name
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public void setAuthorityName(String authorityName) {
		this.authorityName = authorityName == null ? null : authorityName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column beauty_authority.authority_code
	 *
	 * @return the value of beauty_authority.authority_code
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public String getAuthorityCode() {
		if (authorityCode != null) {
			authorityCode = authorityCode.toUpperCase();
		}
		return authorityCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column beauty_authority.authority_code
	 *
	 * @param authorityCode
	 *            the value for beauty_authority.authority_code
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public void setAuthorityCode(String authorityCode) {
		this.authorityCode = authorityCode == null ? null : authorityCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column beauty_authority.group_id
	 *
	 * @return the value of beauty_authority.group_id
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public Long getGroupId() {
		return groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column beauty_authority.group_id
	 *
	 * @param groupId
	 *            the value for beauty_authority.group_id
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public void setGroupId(Long groupId) {
		this.groupId = groupId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column beauty_authority.group_name
	 *
	 * @return the value of beauty_authority.group_name
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public String getGroupName() {
		return groupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column beauty_authority.group_name
	 *
	 * @param groupName
	 *            the value for beauty_authority.group_name
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName == null ? null : groupName.trim();
	}
}