package com.beauty.entity.security2;

import com.beauty.base.security.RecommonEntity;

public class AuthorityReResource extends RecommonEntity {

	/**
	 * @Fields serialVersionUID
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column beauty_authority_resource.resourceId
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	private Long resourceid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column beauty_authority_resource.authorityId
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	private Long authorityid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column beauty_authority_resource.resourceId
	 *
	 * @return the value of beauty_authority_resource.resourceId
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public Long getResourceid() {
		return resourceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column beauty_authority_resource.resourceId
	 *
	 * @param resourceid
	 *            the value for beauty_authority_resource.resourceId
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public void setResourceid(Long resourceid) {
		this.resourceid = resourceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column beauty_authority_resource.authorityId
	 *
	 * @return the value of beauty_authority_resource.authorityId
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public Long getAuthorityid() {
		return authorityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column beauty_authority_resource.authorityId
	 *
	 * @param authorityid
	 *            the value for beauty_authority_resource.authorityId
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public void setAuthorityid(Long authorityid) {
		this.authorityid = authorityid;
	}
}