package com.beauty.entity.security2;

import com.beauty.base.security.CommonEntity;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Group extends CommonEntity {

	/**
	 * @Fields serialVersionUID
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column beauty_group.group_name
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	private String groupName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column beauty_group.group_code
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	private String groupCode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column beauty_group.group_name
	 *
	 * @return the value of beauty_group.group_name
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public String getGroupName() {
		return groupName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column beauty_group.group_name
	 *
	 * @param groupName
	 *            the value for beauty_group.group_name
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public void setGroupName(String groupName) {
		this.groupName = groupName == null ? null : groupName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column beauty_group.group_code
	 *
	 * @return the value of beauty_group.group_code
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public String getGroupCode() {
		if (null != groupCode) {
			return groupCode.toUpperCase();
		}
		return groupCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column beauty_group.group_code
	 *
	 * @param groupCode
	 *            the value for beauty_group.group_code
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public void setGroupCode(String groupCode) {
		this.groupCode = groupCode == null ? null : groupCode.trim();
	}

}