package com.beauty.entity.security2;

import com.beauty.base.security.RecommonEntity;

public class RoleReAuthority extends RecommonEntity {

    /**
	 * @Fields serialVersionUID
	 */
	private static final long serialVersionUID = 1L;

	/**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beauty_role_authority.roleId
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    private Long roleid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column beauty_role_authority.authorityId
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    private Long authorityid;


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beauty_role_authority.roleId
     *
     * @return the value of beauty_role_authority.roleId
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    public Long getRoleid() {
        return roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beauty_role_authority.roleId
     *
     * @param roleid the value for beauty_role_authority.roleId
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    public void setRoleid(Long roleid) {
        this.roleid = roleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column beauty_role_authority.authorityId
     *
     * @return the value of beauty_role_authority.authorityId
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    public Long getAuthorityid() {
        return authorityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column beauty_role_authority.authorityId
     *
     * @param authorityid the value for beauty_role_authority.authorityId
     *
     * @mbggenerated Sun May 31 21:29:11 CST 2015
     */
    public void setAuthorityid(Long authorityid) {
        this.authorityid = authorityid;
    }
}