package com.beauty.entity.security2;

import com.beauty.base.security.CommonEntity;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class User extends CommonEntity {

	/**
	 * @Fields serialVersionUID
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column beauty_user.username
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column beauty_user.usercode
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	private String usercode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column beauty_user.password
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column beauty_user.username
	 *
	 * @return the value of beauty_user.username
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column beauty_user.username
	 *
	 * @param username
	 *            the value for beauty_user.username
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username == null ? null : username.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column beauty_user.usercode
	 *
	 * @return the value of beauty_user.usercode
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public String getUsercode() {
		return usercode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column beauty_user.usercode
	 *
	 * @param usercode
	 *            the value for beauty_user.usercode
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public void setUsercode(String usercode) {
		this.usercode = usercode == null ? null : usercode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column beauty_user.password
	 *
	 * @return the value of beauty_user.password
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column beauty_user.password
	 *
	 * @param password
	 *            the value for beauty_user.password
	 *
	 * @mbggenerated Sun May 31 21:29:11 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

}